package com.iths1122.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Model class of 相册.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "hs_album")
public class HsAlbum implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	@Id
	private String albumId;
	
	private String albumName;

	/** 相册描述. */
	private String description;

	/** 相册的访问次数. */
	private Integer visitCount;

	/** 相册创建时间. */
	private Date createTime;

	/** 所属用户. */
	private String userId;

	/** The set of 图片表. */
	@OneToMany(cascade = CascadeType.ALL ,fetch = FetchType.LAZY ,mappedBy = "hsAlbum")
	private Set<HsImages> hsImagesSet;

	/**
	 * Constructor.
	 */
	public HsAlbum() {
		this.hsImagesSet = new HashSet<HsImages>();
	}

	/**
	 * Set the 主键.
	 * 
	 * @param albumId
	 *            主键
	 */
	public void setAlbumId(String albumId) {
		this.albumId = albumId;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getAlbumId() {
		return this.albumId;
	}

	/**
	 * Set the 相册描述.
	 * 
	 * @param description
	 *            相册描述
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the 相册描述.
	 * 
	 * @return 相册描述
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the 相册的访问次数.
	 * 
	 * @param visitCount
	 *            相册的访问次数
	 */
	public void setVisitCount(Integer visitCount) {
		this.visitCount = visitCount;
	}

	/**
	 * Get the 相册的访问次数.
	 * 
	 * @return 相册的访问次数
	 */
	public Integer getVisitCount() {
		return this.visitCount;
	}

	/**
	 * Set the 相册创建时间.
	 * 
	 * @param createTime
	 *            相册创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 相册创建时间.
	 * 
	 * @return 相册创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 所属用户.
	 * 
	 * @param userId
	 *            所属用户
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the 所属用户.
	 * 
	 * @return 所属用户
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the set of the 图片表.
	 * 
	 * @param hsImagesSet
	 *            The set of 图片表
	 */
	public void setHsImagesSet(Set<HsImages> hsImagesSet) {
		this.hsImagesSet = hsImagesSet;
	}

	/**
	 * Add the 图片表.
	 * 
	 * @param hsImages
	 *            图片表
	 */
	public void addHsImages(HsImages hsImages) {
		this.hsImagesSet.add(hsImages);
	}

	/**
	 * Get the set of the 图片表.
	 * 
	 * @return The set of 图片表
	 */
	public Set<HsImages> getHsImagesSet() {
		return this.hsImagesSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((albumId == null) ? 0 : albumId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HsAlbum other = (HsAlbum) obj;
		if (albumId == null) {
			if (other.albumId != null) {
				return false;
			}
		} else if (!albumId.equals(other.albumId)) {
			return false;
		}
		return true;
	}

	public String getAlbumName() {
		return albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

}
