package com.iths1122.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Model class of 文章表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class HsArticle implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	@Id
	private String articleId;

	/** 标题. */
	private String title;

	/** 摘要. */
	private String digest;

	/** 内容. */
	private String content;

	/** 创建时间. */
	private Date createTime;

	/** 修改时间. */
	private Date updateTime;

	/** 所属用户. */
	private String userId;

	/**
	 * Constructor.
	 */
	public HsArticle() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param articleId
	 *            主键
	 */
	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getArticleId() {
		return this.articleId;
	}

	/**
	 * Set the 标题.
	 * 
	 * @param title
	 *            标题
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the 标题.
	 * 
	 * @return 标题
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the 摘要.
	 * 
	 * @param digest
	 *            摘要
	 */
	public void setDigest(String digest) {
		this.digest = digest;
	}

	/**
	 * Get the 摘要.
	 * 
	 * @return 摘要
	 */
	public String getDigest() {
		return this.digest;
	}

	/**
	 * Set the 内容.
	 * 
	 * @param content
	 *            内容
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * Get the 内容.
	 * 
	 * @return 内容
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 修改时间.
	 * 
	 * @param updateTime
	 *            修改时间
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 修改时间.
	 * 
	 * @return 修改时间
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the 所属用户.
	 * 
	 * @param userId
	 *            所属用户
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the 所属用户.
	 * 
	 * @return 所属用户
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((articleId == null) ? 0 : articleId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HsArticle other = (HsArticle) obj;
		if (articleId == null) {
			if (other.articleId != null) {
				return false;
			}
		} else if (!articleId.equals(other.articleId)) {
			return false;
		}
		return true;
	}

}
