package com.iths1122.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Model class of 图片表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "hs_images")
public class HsImages implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	@Id
	private String imageId;

	/** 图片名称. */
	private String imageName;

	/** 图片地址. */
	private String imageUrl;

	/** 上传时间. */
	private Date uploadTime;

	/** 相册. */
	@ManyToOne(cascade = {CascadeType.MERGE , CascadeType.REFRESH} , fetch = FetchType.LAZY , optional = false )
	@JoinColumn(name = "album_id")
	@JsonIgnore
	private HsAlbum hsAlbum;

	/**
	 * Constructor.
	 */
	public HsImages() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param imageId
	 *            主键
	 */
	public void setImageId(String imageId) {
		this.imageId = imageId;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getImageId() {
		return this.imageId;
	}

	/**
	 * Set the 图片名称.
	 * 
	 * @param imageName
	 *            图片名称
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	/**
	 * Get the 图片名称.
	 * 
	 * @return 图片名称
	 */
	public String getImageName() {
		return this.imageName;
	}

	/**
	 * Set the 图片地址.
	 * 
	 * @param imageUrl
	 *            图片地址
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * Get the 图片地址.
	 * 
	 * @return 图片地址
	 */
	public String getImageUrl() {
		return this.imageUrl;
	}

	/**
	 * Set the 上传时间.
	 * 
	 * @param uploadTime
	 *            上传时间
	 */
	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	/**
	 * Get the 上传时间.
	 * 
	 * @return 上传时间
	 */
	public Date getUploadTime() {
		return this.uploadTime;
	}

	/**
	 * Set the 相册.
	 * 
	 * @param hsAlbum
	 *            相册
	 */
	public void setHsAlbum(HsAlbum hsAlbum) {
		this.hsAlbum = hsAlbum;
	}

	/**
	 * Get the 相册.
	 * 
	 * @return 相册
	 */
	public HsAlbum getHsAlbum() {
		return this.hsAlbum;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((imageId == null) ? 0 : imageId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HsImages other = (HsImages) obj;
		if (imageId == null) {
			if (other.imageId != null) {
				return false;
			}
		} else if (!imageId.equals(other.imageId)) {
			return false;
		}
		return true;
	}

}
