package com.iths1122.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Model class of hs_leave_word.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class HsLeaveWord implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 主键. */
	@Id
	private String lwId;

	/** 留言内容. */
	private String content;

	/** hs_visit_count. */
	private HsVisitCount hsVisitCount;

	/** 字典表. */
	private HsDictionary hsDictionary;

	/** 被留言对象ID. */
	private String belongId;

	/**
	 * Constructor.
	 */
	public HsLeaveWord() {
	}

	/**
	 * Set the 主键.
	 * 
	 * @param lwId
	 *            主键
	 */
	public void setLwId(String lwId) {
		this.lwId = lwId;
	}

	/**
	 * Get the 主键.
	 * 
	 * @return 主键
	 */
	public String getLwId() {
		return this.lwId;
	}

	/**
	 * Set the 留言内容.
	 * 
	 * @param content
	 *            留言内容
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * Get the 留言内容.
	 * 
	 * @return 留言内容
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * Set the hs_visit_count.
	 * 
	 * @param hsVisitCount
	 *            hs_visit_count
	 */
	public void setHsVisitCount(HsVisitCount hsVisitCount) {
		this.hsVisitCount = hsVisitCount;
	}

	/**
	 * Get the hs_visit_count.
	 * 
	 * @return hs_visit_count
	 */
	public HsVisitCount getHsVisitCount() {
		return this.hsVisitCount;
	}

	/**
	 * Set the 字典表.
	 * 
	 * @param hsDictionary
	 *            字典表
	 */
	public void setHsDictionary(HsDictionary hsDictionary) {
		this.hsDictionary = hsDictionary;
	}

	/**
	 * Get the 字典表.
	 * 
	 * @return 字典表
	 */
	public HsDictionary getHsDictionary() {
		return this.hsDictionary;
	}

	/**
	 * Set the 被留言对象ID.
	 * 
	 * @param belongId
	 *            被留言对象ID
	 */
	public void setBelongId(String belongId) {
		this.belongId = belongId;
	}

	/**
	 * Get the 被留言对象ID.
	 * 
	 * @return 被留言对象ID
	 */
	public String getBelongId() {
		return this.belongId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lwId == null) ? 0 : lwId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		HsLeaveWord other = (HsLeaveWord) obj;
		if (lwId == null) {
			if (other.lwId != null) {
				return false;
			}
		} else if (!lwId.equals(other.lwId)) {
			return false;
		}
		return true;
	}

}
